MSensis/Controllers/MSensisController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DinkToPdf;
using DinkToPdf.Contracts; 
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MSensis.Models;
using MSensis.Services;
using MSensis.ViewModels;
 
namespace MSensis.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class MSensisController : ControllerBase
    {
         
        private readonly MSensisContext _db;
        private readonly UserManager<User> _manager;
        private IConverter _converter;
      
        private readonly ILogger<MSensisController> _logger;
        private readonly IHostingEnvironment _env;
        



        public MSensisController(MSensisContext _db, UserManager<User> manager, IConverter converter,  
            ILogger<MSensisController> logger, IHostingEnvironment env )
        {
            this._db = _db;
            _manager = manager;
            _converter = converter; 
            _logger =logger;
            _env = env;
           
        }

       

        [HttpPost]
            public bool Delete_Invoice(string id)
            {
            Invoice i = _db.Invoices.SingleOrDefault(u => u.Id == id);

            Pdf p = _db.Pdfs.SingleOrDefault(u => u.Invoice.Id == id);
            try
            {
                if (p != null && i != null)
                {
                    _db.Remove(p);
                    _db.Remove(i);
                    _db.SaveChangesAsync();
                    return true;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"{ex}");
            }

            return false;
            }

            [HttpPost]
            public bool Delete_Client(string id)
            {
            Client i = _db.Clients.SingleOrDefault(u => u.Id == id);
            if( i != null)
            {
                _db.Remove(i);
                _db.SaveChangesAsync();
                return true;
            }
             return false;

             }

        [HttpPost]
        public bool Delete_Company(string id)
        {
            Company i = _db.Companies.SingleOrDefault(u => u.Id == id);
            try
            {
                if (i != null)
                {
                    _db.Remove(i);
                    _db.SaveChangesAsync();
                    return true;
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"{ex}");
            }
            return false;
        }


        public async Task<IActionResult> Issue_Invoice(string id)
        {
            var invoice = _db.Invoices.SingleOrDefault(u => u.Id == id);

            try
            {
                using (var db = new MSensisContext())
                {
                    invoice.Invoice_Type = "Issued";
                    await _db.SaveChangesAsync();
                    return RedirectToAction("IssuedPdfs", "Home");
                }
            }
             
            catch (Exception ex)
            {
                _logger.LogError($"{ex}");
            } 
            return BadRequest("badboy");
       }


        public async Task<IActionResult> Ιnvoice_del(string id)
        {
            var invoice = _db.Invoices.SingleOrDefault(u => u.Id == id);

            try
            {
                using (var db = new MSensisContext())
                {
                    invoice.Invoice_Type = "Deleted";
                    await _db.SaveChangesAsync();
                    return RedirectToAction("IssuedPdfs", "Home");
                }
            }

            catch (Exception ex)
            {
                _logger.LogError($"{ex}");
            }
            return BadRequest("badboy");
        }



        public async Task<IActionResult> Download(string id)
        {
            Generator pdf = new Generator(_db, _env);
            return await pdf.CreatePDF(id);
        }

        [HttpGet]
        public async Task<IActionResult> CreatePDF(string id)
        { 
             
                var globalSettings = new GlobalSettings
                {
                    ColorMode = ColorMode.Color,
                    Orientation = Orientation.Portrait,
                    PaperSize = PaperKind.A4,
                    Margins = new MarginSettings { Top = 10 },
                    DocumentTitle = "PDF Report",
                };

                var objectSettings = new ObjectSettings
                {
                    PagesCount = true,
                    Page =  $"https://localhost:44389/Home/Pdf/{id}",
                    WebSettings = { DefaultEncoding = "utf-8", UserStyleSheet = Path.Combine(Directory.GetCurrentDirectory(), "Services", "styles222.css") },
                    HeaderSettings = { FontName = "Arial", FontSize = 9, Right = "Page [page] of [toPage]", Line = true },
                    FooterSettings = { FontName = "Arial", FontSize = 9, Line = true, Center = "Report Footer" },

                };
             
            _logger.LogWarning($"{objectSettings.Page}"); 
                var pdf = new HtmlToPdfDocument()
                {
                    GlobalSettings = globalSettings,
                    Objects = { objectSettings }
                }; 
              
            string url = HttpContext.Request.Path;
            _logger.LogWarning($"{url}");

            var date = DateTime.Now;

            var name = await _db.Pdfs.Where(u => u.Id == id).Select(u => u.Client.CompanyName).SingleOrDefaultAsync();
            if (name == null)
            {
                name = $"PDF{DateTime.Now}";
            }

            var contentType = "application/pdf";
            var fileName = $"{name}-{date.Month}-{date.Year}-{date.Second}.pdf";

            byte[] file = _converter.Convert(pdf);
               //this writes pdf to disk
                using (FileStream stream = new FileStream(@"Files\" + DateTime.UtcNow.Ticks.ToString() + ".pdf", FileMode.Create))
                {
                        stream.Write(file, 0, file.Length);
                 }
	        return new FileContentResult(file, contentType);
        }



       


        public PDFViewModel SearchByMonth(int months)
        {

            var DateList2 = _db.Pdfs.Where(p => p.Timestamp >= DateTime.Today.AddMonths(-months)).Include(u => u.Invoice)
                .ToList();

            string name = _db.Pdfs.Where(p => p.Timestamp >= DateTime.Today.AddMonths(-months)).Include(u => u.Client).Select(u => u.Client.CompanyName).SingleOrDefault();

            PDFViewModel model = new PDFViewModel()
            {
                DataPdf = DateList2,
                CompanyName = name

            };

            return model;
        }

              

            public async Task<IActionResult> LoadCompany([FromBody]UserViewModel model)
        {
            User user = await _manager.GetUserAsync(HttpContext.User);
            Company company = _db.Companies.Where(c => c.Id == model.CompanyId).SingleOrDefault();
            return Ok(company);
        }

         
    }
        public class TestData
        {
            public string Text { get; set; }
            public int Number { get; set; }
        }
    }

MSensis/Views/Shared/Empty.cshtml
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    @RenderBody()
    @RenderSection("scripts", required: false)
    <!-- /.content -->
</div>

MSensis/Views/Shared/_Administrator.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<title>Admin Panel</title>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="~/adminlte/dist/css/AdminLTE.css">
    <link rel="stylesheet" href="~/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="~/css/Lang.css">
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="~/js/jquery-adaptive-background.js"></script>
    <link rel="stylesheet" href="~/bower_components/morris.js/morris.css">
    <link rel="stylesheet" href="~/adminlte/components/jvectormap/jquery-jvectormap.css">

    <link rel="stylesheet" href="~/adminlte/components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/adminlte/components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/adminlte/components/Ionicons/css/ionicons.min.css">
    <script src="~/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="~/dist/css/skins/skin-blue.min.css">
    <link href="https://fonts.googleapis.com/css?family=Passion+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oxygen" rel="stylesheet">
</head>


<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <a href="Home/Index" class="logo">
                <span class="logo-mini"><b>AP</b>T</span>
                <span class="logo-lg"><b>AdminPanel </b></span>
            </a>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="col-sm-6 text-right">
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>
                <div class="navbar-custom-menu">

                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/content/user2-160x160.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">Hello @UserManager.GetUserName(User)!</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="~/content/user2-160x160.jpg" class="img-circle" alt="User Image">
                                    <p>
                                        @UserManager.GetUserName(User)
                                    </p>
                                </li>
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href='@Url.Action("UpdateProfile", "Home")' class="btn btn-default btn-flat">@_localizer["Profile"]</a>
                                    </div>
                                    <div class="pull-right">
                                        <form id="logoutForm" class="form-inline" asp-action="LogOut" asp-controller="Account">
                                            <button id="logout" type="submit" class=btn btn-default btn-flat">@_localizer["Logout"]</button>
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="~/content/user2-160x160.jpg" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p> @UserManager.GetUserName(User) </p>
                    <a href="#"><i class="fa fa-circle text-success"></i> @_localizer["Online"]</a>
                </div>
            </div>

            @Html.Partial("_MainMenu")

        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            @RenderBody()
            <!-- /.content -->
        </div>
        <footer class="main-footer">
            <!-- Default to the left -->
            <strong>Copyright © 2020 . MSensis.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery UI 1.11.4 -->
    <script src="~/adminlte/components/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>$.widget.bridge('uibutton', $.ui.button);</script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Morris.js charts -->
    <script src="~/adminlte/components/raphael/raphael.min.js"></script>
    <script src="~/adminlte/components/morris.js/morris.min.js"></script>
    <!-- Sparkline -->
    <script src="~/adminlte/components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <!-- jvectormap -->
    <script src="~/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/adminlte/components/jquery-knob/dist/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/adminlte/components/moment/min/moment.min.js"></script>
    <script src="~/adminlte/components/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- datepicker -->
    <script src="~/adminlte/components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="~/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
    <script src="~/adminlte/components/chart.js/Chart.js"></script>
    <!-- Slimscroll -->
    <script src="~/adminlte/components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/adminlte/components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlte/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/adminlte/dist/js/pages/dashboard.js"></script>
    <script src="~/adminlte/dist/js/pages/dashboard2.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/adminlte/dist/js/demo.js"></script>
</body>

MSensis/Views/Shared/_AdminlteNetCoreBasicStyles.cshtml
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="~/adminlte/components/bootstrap/dist/css/bootstrap.min.css">
<!-- Font Awesome -->
<link rel="stylesheet" href="~/adminlte/components/font-awesome/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="~/adminlte/components/Ionicons/css/ionicons.min.css">
<!-- Select2 -->
<link rel="stylesheet" href="~/adminlte/components/select2/dist/css/select2.min.css">
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="~/adminlte/components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
<!-- DataTables -->
<link rel="stylesheet" href="~/adminlte/components/datatables.net-bs/css/dataTables.bootstrap.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="~/adminlte/dist/css/AdminLTE.min.css">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="~/adminlte/dist/css/skins/_all-skins.min.css">
<!-- Pace style -->
<link rel="stylesheet" href="~/adminlte/plugins/pace/pace.min.css">
<!-- Toastr -->
<link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
<!-- Sweetalert -->
<link rel="stylesheet" href="~/lib/sweetalert/sweetalert.css" />
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

MSensis/Views/Shared/_DataTable.cshtml
@using MSensis.ViewModels;
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer

@model ClientViewModel
<!-- /.box-header -->
<div class="box-body">
    <table id="example1" class="table table-bordered table-striped">
        <thead>
            <tr>

                <th>@_localizer["Company"]</th>
                <th>@_localizer["Client"]</th>
                <th>@_localizer["Invoice Date"]</th>
                <th> @_localizer["Print pdf"]</th>
                <th> @_localizer["See document"]</th>
                <th> @_localizer["Update Invoice"]</th>
                <th> @_localizer["Delete Invoice"]</th>
                <th> @_localizer["Issue Invoice"]</th>
           </tr>
        </thead>
        @foreach (var item in Model.Pdfs)
        {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Company.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.Client.CompanyName)</td>
            <td>@Html.DisplayFor(modelItem => item.Invoice.Timestamp)</td>
            <td>  <a asp-action="CreatePDF" asp-controller="MSensis" asp-route-id="@item.Id">@_localizer["Download Pdf"] <i class="fa fa-download"></i></a></td>
            <td>  <a asp-action="ViewPdf" asp-controller="Home" asp-route-id="@item.Id">@_localizer["View"] <i class="fa fa-eye"></i></a> </td>
            <td>
                <a asp-action="Update_Invoice" asp-route-id="@item.Invoice.Id">@_localizer["Update"] <i class="fa fa-edit"></i></a>

            </td>
            <td>
                <a asp-action="Ιnvoice_del" asp-controller="MSensis" asp-route-id="@item.Invoice.Id" data-toggle="tooltip" data-position="top" data-delay="50" data-tooltip="Download PDF"
                   style="padding-right: 2px;">@_localizer["Delete Invoice"]<i class="fa fa-edit"></i></a>
            </td>
            <td>
                <a asp-action="Issue_Invoice" asp-controller="MSensis" asp-route-id="@item.Invoice.Id">@_localizer["Issue Invoice"] <i class="fa fa-edit"></i></a>
            </td>

        </tr>
        }

    </table>
</div>

         

MSensis/Views/Shared/_DataTable2.cshtml
@using  MSensis.ViewModels;
@model ClientViewModel





<div class="box-body">
    <table id="example1" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Company</th>
                <th>Client</th>
                <th>Invoice Date</th>
                <th> Invoice type</th>
                <th> Print pdf</th>
                <th> View Document</th>
                <th> Update Invoice</th>
                <th> View Products</th>
                <th> Total Vat</th>
                <th> Total Value</th>
                <th>Issue invoice</th>
                <th>Delete invoice</th>
            </tr>
        </thead>
        @foreach (var item in Model.Pdfs)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Company.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Client.CompanyName)</td>
                <td>@item.Invoice.Timestamp.Value.ToString("dd'/'MM'/'yyyy")</td>
                <td>@Html.DisplayFor(modelItem => item.Invoice.Invoice_Type)</td>

                <td>  <a asp-action="ViewPdf" asp-controller="Home" asp-route-id="@item.Id">Download Pdf <i class="fa fa-download"></i></a>       </td>

                <td>  <a asp-action="ViewInvoice" asp-controller="Home" asp-route-id="@item.Id">View <i class="fa fa-eye"></i></a> </td>
                <td>
                    <a asp-action="Update_Invoice" asp-route-id="@item.Invoice.Id">Update <i class="fa fa-edit"></i></a>
                </td>
                <td>
                    <a asp-action="ViewProducts" asp-route-id="@item.Id" data-toggle="tooltip" data-position="top" data-delay="50" data-tooltip="Download PDF"
                       style="padding-right: 2px;">View Products<i class="fa fa-edit"></i></a>
                </td>
                <td>
                    @item.TotalVat.ToString("#.##")
                </td>
                <td>
                    @item.TotalValue.ToString("#.##")
                </td>
                <td>
                    <a asp-action="Issue_Invoice" asp-controller="MSensis" asp-route-id="@item.Invoice.Id" data-toggle="tooltip" data-position="top" data-delay="50" data-tooltip="Download PDF"
                       style="padding-right: 2px;">Issue Invoice<i class="fa fa-edit"></i></a>

                </td>

                <td>
                    <a asp-action="Ιnvoice_del" asp-controller="MSensis" asp-route-id="@item.Invoice.Id" data-toggle="tooltip" data-position="top" data-delay="50" data-tooltip="Delete Invoice"
                       style="padding-right: 2px;">Delete Invoice<i class="fa fa-trash-o"></i></a>

                </td>

            </tr>
        }

    </table>
</div>


<script>
      $(function () {
        $('#example1').DataTable();
    });
</script>

MSensis/Views/Shared/_DataTable3.cshtml
@using MSensis.ViewModels
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer

@model ClientViewModel



<div class="box-body">
    <table id="example1" class="table table-bordered table-striped">
        <thead>

            <tr>
                <th>@_localizer["Company"]</th>
                <th>@_localizer["Client"]</th>
                <th>@_localizer["Invoice Date"]</th>
                <th> @_localizer["Invoice type"]</th>
                <th> @_localizer["View Document"]</th>
                <th> @_localizer["Update Invoice"]</th>
                <th> @_localizer["View Products"]</th>
                <th>@_localizer["Delete Invoice"]</th>
                <th> @_localizer["Total Vat"]</th>
                <th> @_localizer["Total Value"]</th>
           </tr>

        </thead>
        @foreach (var item in Model.Pdfs)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Company.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Client.CompanyName)</td>
                <td>@item.Invoice.Timestamp.Value.ToString("dd'/'MM'/'yyyy")</td>
                <td>@Html.DisplayFor(modelItem => item.Invoice.Invoice_Type)</td>

                <td>  <a asp-action="ViewInvoice" asp-controller="Home" asp-route-id="@item.Id">@_localizer["View"] <i class="fa fa-eye"></i></a> </td>
                <td>
                    <a asp-action="Update_Invoice" asp-route-id="@item.Invoice.Id">@_localizer["Update"] <i class="fa fa-edit"></i></a>
                </td>
                <td>
                    <a asp-action="ViewProducts" asp-route-id="@item.Id" data-toggle="tooltip" data-position="top" data-delay="50" data-tooltip="Download PDF"
                       style="padding-right: 2px;">@_localizer["View Products"]<i class="fa fa-edit"></i></a>
                </td>
                <td>
                    <a asp-action="Ιnvoice_del" asp-controller="MSensis" asp-route-id="@item.Invoice.Id" data-toggle="tooltip" data-position="top" data-delay="50" data-tooltip="Download PDF"
                       style="padding-right: 2px;">@_localizer["Delete Invoice"]<i class="fa fa-edit"></i></a>

                </td>
                <td>
                    @item.TotalVat.ToString("#.##")
                </td>
                <td>
                    @item.TotalValue.ToString("#.##")
                </td>

            </tr>
        }
    </table>
</div>

<script>
      $(function () {
        $('#example1').DataTable();
    });
</script>

MSensis/Views/Shared/_DataTableInvoice.cshtml
@using MSensis.ViewModels;
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer

@model ClientViewModel


@{
    ViewData["Title"] = "Delete";
}


<!-- Main content -->

   

                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>@_localizer["Company"]</th>
                                <th>@_localizer["Client"]</th>
                                <th>@_localizer["Invoice Date"]</th>
                                <th> @_localizer["Invoice type"]</th>
                                <th> @_localizer["Print pdf"]</th>
                                <th> @_localizer["View Document"]</th>
                                <th> @_localizer["Update Invoice"]</th>
                                <th> @_localizer["View Products"]</th>
                                <th> @_localizer["Total Vat"]</th>
                                <th> @_localizer["Total Value"]</th>
                                <th>@_localizer["Issue Invoice"]</th>
                                <th>@_localizer["Delete Invoice"]</th>
                            </tr>
                        </thead>
                        @foreach (var item in Model.Pdfs)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Company.Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.Client.CompanyName)</td>
                                <td>@Html.DisplayFor(modelItem => item.Invoice.Timestamp)</td>
                                <td>@Html.DisplayFor(modelItem => item.Invoice.Invoice_Type)</td>

                                <td>  <a asp-action="CreatePDF" asp-controller="MSensis" asp-route-id="@item.Id">@_localizer["Download Pdf"] <i class="fa fa-download"></i></a></td>

                                <td>  <a asp-action="ViewInvoice" asp-controller="Home" asp-route-id="@item.Id">@_localizer["View"] <i class="fa fa-eye"></i></a> </td>
                                <td>
                                    <a asp-action="Update_Invoice" asp-route-id="@item.Invoice.Id">@_localizer["Update"] <i class="fa fa-edit"></i></a>
                                </td>
                                <td>
                                    <a asp-action="ViewProducts" asp-route-id="@item.Id" data-toggle="tooltip" data-position="top" data-delay="50" data-tooltip="Download PDF"
                                       style="padding-right: 2px;">@_localizer["View Products"]<i class="fa fa-edit"></i></a>
                                </td>
                                <td>
                                    @item.TotalVat.ToString("#.##")
                                </td>
                                <td>
                                    @item.TotalValue.ToString("#.##")
                                </td>
                                <td>
                                    <a asp-action="Issue_Invoice" asp-controller="MSensis" asp-route-id="@item.Invoice.Id" data-toggle="tooltip" data-position="top" data-delay="50" data-tooltip="Download PDF"
                                       style="padding-right: 2px;">@_localizer["Issue Invoice"]<i class="fa fa-edit"></i></a>

                                </td>

                                <td>
                                    <a asp-action="Ιnvoice_del" asp-controller="MSensis" asp-route-id="@item.Invoice.Id" data-toggle="tooltip" data-position="top" data-delay="50" data-tooltip="Delete Invoice"
                                       style="padding-right: 2px;">@_localizer["Delete Invoice"]<i class="fa fa-trash-o"></i></a>

                                </td>

                            </tr>
                        }

                    </table>

                </div>
<script>
     $(function () {
        $('#example1').DataTable();
    });
</script>